CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE collections (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    collection_name TEXT UNIQUE NOT NULL,
    description TEXT,
    ai_model_name TEXT,
    dimensions INT NOT NULL,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- single-table
CREATE TABLE embeddings (
    collection_id BIGINT REFERENCES collections(id) ON DELETE CASCADE,
    embedding_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    embedding VECTOR NOT NULL, -- different sizes, requires more careful expression indexing
    authz_version INT NOT NULL,  -- future flexibility in case we need to change this whole authz schema/method. there's no real extensibility built in yet, but this will at least form a starting point for knowing this is a v0 authz record. idk I guess we'd have to migrate anyway, but if we wanted two versions in different records at the same time, this might be useful?
    authz TEXT[] NOT NULL,
    metadata JSONB DEFAULT '{}'::JSONB,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),

    -- avoid duplicates inside the same collection
    CONSTRAINT uniq_collection_uuid UNIQUE (collection_id, embedding_id)
);


-- may need to consider partitioning eventually...

-- indexing will need to be dynamic for same-dim vectors
-- CONCURRENTLY allows it to safely run in prod during other read/write operations (at the cost of increased time and resource usage)
-- NOTE: if we end up needing to partition, we can't use CONCURRENTLY
-- Concurrent builds for indexes on partitioned tables are currently not supported in postgres.
-- CREATE INDEX CONCURRENTLY ON embeddings USING hnsw ((embedding::vector(512)) vector_l2_ops) WHERE (collection_id = 2);

-- JSONB column metadata inverted index, so value searching on tags or something
-- is optimized
CREATE INDEX idx_embeddings_metadata_gin
    ON embeddings
    USING GIN (metadata);

-- on authz tags for faster filtering, similar to above
CREATE INDEX idx_embeddings_authz_gin
    ON embeddings
    USING GIN (authz);

-- row level security will enforce authz
ALTER TABLE embeddings
  ENABLE ROW LEVEL SECURITY;

-- we can use row level security by setting a local var in
-- postgres and then reading it here. so before this, we SET LOCAL
-- allowed_authz to the user's allowed authz resources from arborist
-- applies to ALL (SELECT, INSERT, UPDATE, DELETE)
CREATE POLICY authz_policy ON embeddings
  USING (
    -- reminder: authz is a TEXT[], so the GIN above makes this fast
    authz && current_setting('app.allowed_authz', true)::text[]
    AND authz_version = 0
  )
  WITH CHECK (
    -- reminder: authz is a TEXT[], so the GIN above makes this fast
    authz && current_setting('app.allowed_authz', true)::text[]
    AND authz_version = 0
  );
