CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS collections (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    collection_name TEXT UNIQUE NOT NULL,
    description TEXT,
    ai_model_name TEXT,
    dimensions INT NOT NULL,
    vector_type TEXT NOT NULL DEFAULT 'vector',

    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS embeddings_vector (
    collection_id BIGINT REFERENCES collections(id) ON DELETE CASCADE,
    embedding_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    embedding VECTOR NOT NULL,
    authz TEXT[] NOT NULL,
    metadata JSONB DEFAULT '{}'::JSONB,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),

    CONSTRAINT embeddings_vector_uniq_collection_uuid UNIQUE (collection_id, embedding_id)
);

CREATE TABLE IF NOT EXISTS embeddings_halfvec (
    collection_id BIGINT REFERENCES collections(id) ON DELETE CASCADE,
    embedding_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    embedding HALFVEC NOT NULL,
    authz TEXT[] NOT NULL,
    metadata JSONB DEFAULT '{}'::JSONB,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),

    CONSTRAINT embeddings_halfvec_uniq_collection_uuid UNIQUE (collection_id, embedding_id)
);


-- may need to consider partitioning eventually...

-- indexing will need to be dynamic for same-dim vectors
-- CONCURRENTLY allows it to safely run in prod during other read/write operations (at the cost of increased time and resource usage)
-- NOTE: if we end up needing to partition, we can't use CONCURRENTLY
-- Concurrent builds for indexes on partitioned tables are currently not supported in postgres.
-- CREATE INDEX CONCURRENTLY ON embeddings USING hnsw ((embedding::vector(512)) vector_l2_ops) WHERE (collection_id = 2);

-- JSONB column metadata inverted index, so value searching on tags or something
-- is optimized
CREATE INDEX IF NOT EXISTS idx_embeddings_vector_metadata_gin
    ON embeddings_vector USING GIN (metadata);

CREATE INDEX IF NOT EXISTS idx_embeddings_halfvec_metadata_gin
    ON embeddings_halfvec USING GIN (metadata);

-- on authz tags for faster filtering, similar to above
CREATE INDEX IF NOT EXISTS idx_embeddings_vector_authz_gin
    ON embeddings_vector USING GIN (authz);

CREATE INDEX IF NOT EXISTS idx_embeddings_halfvec_authz_gin
    ON embeddings_halfvec USING GIN (authz);

-- row level security will enforce authz
ALTER TABLE embeddings_vector ENABLE ROW LEVEL SECURITY;
ALTER TABLE embeddings_halfvec ENABLE ROW LEVEL SECURITY;

-- we can use row level security by setting a local var in
-- postgres and then reading it here. so before this, we SET LOCAL
-- allowed_authz to the user's allowed authz resources from arborist
-- applies to ALL (SELECT, INSERT, UPDATE, DELETE)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM   pg_policies
    WHERE  schemaname = 'public'
      AND  tablename  = 'embeddings_vector'
      AND  policyname = 'authz_policy_vector'
  ) THEN
    CREATE POLICY authz_policy_vector ON embeddings_vector
      USING (
        authz && current_setting('app.allowed_authz', true)::text[]
      )
      WITH CHECK (
        authz && current_setting('app.allowed_authz', true)::text[]
      );
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM   pg_policies
    WHERE  schemaname = 'public'
      AND  tablename  = 'embeddings_halfvec'
      AND  policyname = 'authz_policy_halfvec'
  ) THEN
    CREATE POLICY authz_policy_halfvec ON embeddings_halfvec
      USING (
        authz && current_setting('app.allowed_authz', true)::text[]
      )
      WITH CHECK (
        authz && current_setting('app.allowed_authz', true)::text[]
      );
  END IF;
END;
$$;
