import json
from pathlib import Path
from gen3_embeddings.main import get_app


def main():
    app = get_app()
    schema = app.openapi()
    out_path = Path("docs") / "autogenerated_openapi.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(schema, indent=2))
    print(f"Wrote OpenAPI schema to {out_path}")


if __name__ == "__main__":
    main()
