-- ===========================================================================
-- IMPORTANT! READ! DO NOT SKIP THIS!!
-- ===========================================================================
-- We need to follow an expand/contract pattern for db migrations for safety.
-- e.g. if you are replacing a column or doing anything that would BREAK running
--      services, stop. Do not do that. Instead, _expand_ the current schema to ONLY ADD
--      new things which are not breaking. Then, once everyone has completed that migration,
--      _contract_ the schema, actually doing the removal of anything you wanted to.
--
-- IMPORTANT QUESTIONS:
-- 1. Is this change backwards compatible with running application pods?
--      - Yes? Great, you're following the "expand" correctly. Now consider when and how you should "contract".
--      - No? Stop. You could break production. You need the OLD application code to work with the NEW database
--        and the NEW application code to work with the NEW database. Eventually, when you apply the "contract" migration, the
--        OLD logic can be safely removed (assuming everyone has migrated to the expansion).
-- 2. DO NOT drop or rename columns in an initial migration. Use a multi-stage rollout
--      - Add new column in one migration, remove old in a FUTURE migration after everyone is on the first one
-- 3. If you are only adding a heavy index, consider adding "transaction:false" to the migrate line
--    and use CREATE INDEX CONCURRENTLY.
--    Changing "-- migrate:up" to "-- migrate:up transaction:false" tells dbmate to turn OFF transactional
--    migrations.
--
--    If you don't do this and your migration takes a long time, it will block live operations (read/write).
--    You can use CONCURRENTLY to not block and allow read/write while
--    the action happens in the background in the db, but only if you tell dbmate to not put the whole migration
--    in a transaction.
--
--    NOTE: Heavy indexes may take longer than the statement_timeout default below. If building a large index,
--          manually add "SET statement_timeout = '0';" (disabled) or some other reasonable maximum. Just note
--          that postgres will kill a statement after that maximum.
--
-- ===========================================================================
-- UPGRADE MIGRATION SQL
-- ===========================================================================
-- migrate:up
--
-- ==== guardrails: prod safety ====
-- in postgres, while a migration waits for a lock, it blocks ALL live app traffic
-- behind it in the queue.
--
-- lock_timeout:      If the migration can't get a lock within n seconds (e.g. stuck
--                    behind a slow app query), it aborts safely to protect the live app traffic.
-- statement_timeout: If the migration gets the lock but takes longer than n seconds
--                    to run, it aborts so it doesn't hold the DB hostage.
SET lock_timeout = '10s';
SET statement_timeout = '60s';

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS collections (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  collection_name TEXT UNIQUE NOT NULL,
  description TEXT,
  ai_model_name TEXT,
  dimensions INT NOT NULL,
  vector_type TEXT NOT NULL DEFAULT 'vector',

  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS embeddings_vector (
  collection_id BIGINT REFERENCES collections (id) ON DELETE CASCADE,
  embedding_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  embedding VECTOR NOT NULL,
  authz TEXT [] NOT NULL,
  metadata JSONB DEFAULT '{}'::JSONB,

  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),

  CONSTRAINT embeddings_vector_uniq_collection_uuid UNIQUE (
    collection_id, embedding_id
  )
);

CREATE TABLE IF NOT EXISTS embeddings_halfvec (
  collection_id BIGINT REFERENCES collections (id) ON DELETE CASCADE,
  embedding_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  embedding HALFVEC NOT NULL,
  authz TEXT [] NOT NULL,
  metadata JSONB DEFAULT '{}'::JSONB,

  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),

  CONSTRAINT embeddings_halfvec_uniq_collection_uuid UNIQUE (
    collection_id, embedding_id
  )
);


-- may need to consider partitioning eventually...

-- indexing will need to be dynamic for same-dim vectors
-- CONCURRENTLY allows it to safely run in prod during other read/write operations (at the cost of increased time and resource usage)
-- NOTE: if we end up needing to partition, we can't use CONCURRENTLY
-- Concurrent builds for indexes on partitioned tables are currently not supported in postgres.
-- CREATE INDEX CONCURRENTLY ON embeddings USING hnsw ((embedding::vector(512)) vector_l2_ops) WHERE (collection_id = 2);

-- JSONB column metadata inverted index, so value searching on tags or something
-- is optimized
CREATE INDEX IF NOT EXISTS idx_embeddings_vector_metadata_gin
ON embeddings_vector USING gin (metadata);

CREATE INDEX IF NOT EXISTS idx_embeddings_halfvec_metadata_gin
ON embeddings_halfvec USING gin (metadata);

-- on authz tags for faster filtering, similar to above
CREATE INDEX IF NOT EXISTS idx_embeddings_vector_authz_gin
ON embeddings_vector USING gin (authz);

CREATE INDEX IF NOT EXISTS idx_embeddings_halfvec_authz_gin
ON embeddings_halfvec USING gin (authz);

-- row level security will enforce authz
ALTER TABLE embeddings_vector ENABLE ROW LEVEL SECURITY;
ALTER TABLE embeddings_halfvec ENABLE ROW LEVEL SECURITY;

-- Enforce no duplicate embeddings in the same collection for vector type
ALTER TABLE embeddings_vector
ADD CONSTRAINT embeddings_vector_uniq_collection_vector
UNIQUE (collection_id, embedding);
ALTER TABLE embeddings_halfvec
ADD CONSTRAINT embeddings_halfvec_uniq_collection_vector
UNIQUE (collection_id, embedding);

-- we can use row level security by setting a local var in
-- postgres and then reading it here. so before this, we SET LOCAL
-- allowed_authz to the user's allowed authz resources from arborist
-- applies to ALL (SELECT, INSERT, UPDATE, DELETE)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM   pg_policies
    WHERE  schemaname = 'public'
      AND  tablename  = 'embeddings_vector'
      AND  policyname = 'authz_policy_vector'
  ) THEN
    CREATE POLICY authz_policy_vector ON embeddings_vector
      USING (
        authz && current_setting('app.allowed_authz', true)::text[]
      )
      WITH CHECK (
        authz && current_setting('app.allowed_authz', true)::text[]
      );
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM   pg_policies
    WHERE  schemaname = 'public'
      AND  tablename  = 'embeddings_halfvec'
      AND  policyname = 'authz_policy_halfvec'
  ) THEN
    CREATE POLICY authz_policy_halfvec ON embeddings_halfvec
      USING (
        authz && current_setting('app.allowed_authz', true)::text[]
      )
      WITH CHECK (
        authz && current_setting('app.allowed_authz', true)::text[]
      );
  END IF;
END;
$$;

-- ===========================================================================
-- DOWNGRADE MIGRATION SQL
-- ===========================================================================
-- migrate:down
SET lock_timeout = '10s';
SET statement_timeout = '60s';

DROP TABLE IF EXISTS collections CASCADE;
DROP TABLE IF EXISTS embeddings_vector CASCADE;
DROP TABLE IF EXISTS embeddings_halfvec CASCADE;

DROP EXTENSION IF EXISTS vector;
