-- migrate:up

-- ============================================================
-- MODEL REPOSITORIES
-- ============================================================

CREATE TABLE IF NOT EXISTS model_repositories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    namespace VARCHAR(255) NOT NULL,
    repo_name VARCHAR(255) NOT NULL,

    description TEXT,

    tags TEXT[] DEFAULT '{}',

    current_revision VARCHAR(255) DEFAULT 'main',

    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    UNIQUE(namespace, repo_name)
);

CREATE INDEX IF NOT EXISTS idx_model_repositories_namespace_repo
ON model_repositories(namespace, repo_name);

CREATE INDEX IF NOT EXISTS idx_model_repositories_namespace
ON model_repositories(namespace);

CREATE INDEX IF NOT EXISTS idx_model_repositories_revision
ON model_repositories(current_revision);

-- ============================================================
-- UPDATED_AT TRIGGER
-- ============================================================

CREATE OR REPLACE FUNCTION update_model_repositories_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_model_repositories_updated_at
ON model_repositories;

CREATE TRIGGER update_model_repositories_updated_at
BEFORE UPDATE ON model_repositories
FOR EACH ROW
EXECUTE FUNCTION update_model_repositories_updated_at();

-- ============================================================
-- MODEL REVISIONS
-- ============================================================

CREATE TABLE IF NOT EXISTS model_revisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    repository_id BIGINT NOT NULL
        REFERENCES model_repositories(id)
        ON DELETE CASCADE,

    revision_name VARCHAR(255) NOT NULL DEFAULT 'main',

    revision_identifier VARCHAR(255),

    etag VARCHAR(255),

    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    UNIQUE(repository_id, revision_name)
);

CREATE INDEX IF NOT EXISTS idx_model_revisions_repo
ON model_revisions(repository_id);

CREATE INDEX IF NOT EXISTS idx_model_revisions_revision
ON model_revisions(repository_id, revision_name);

-- ============================================================
-- MODEL FILES
-- ============================================================

CREATE TABLE IF NOT EXISTS model_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    revision_id BIGINT NOT NULL
        REFERENCES model_revisions(id)
        ON DELETE CASCADE,

    file_path VARCHAR(1024) NOT NULL,

    s3_key VARCHAR(2048) NOT NULL,

    file_size BIGINT NOT NULL,

    content_sha VARCHAR(64),

    content_etag VARCHAR(255),

    file_type VARCHAR(50),

    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    UNIQUE(revision_id, file_path)
);

CREATE INDEX IF NOT EXISTS idx_model_files_revision
ON model_files(revision_id);

CREATE INDEX IF NOT EXISTS idx_model_files_path
ON model_files(revision_id, file_path);

CREATE INDEX IF NOT EXISTS idx_model_files_sha
ON model_files(content_sha);

CREATE INDEX IF NOT EXISTS idx_model_files_s3_key
ON model_files(s3_key);

-- ============================================================
-- COMMENTS
-- ============================================================

COMMENT ON TABLE model_repositories IS
'Top-level model repositories similar to Hugging Face repositories';

COMMENT ON TABLE model_revisions IS
'Repository revisions such as main, v1, v2, release candidates';

COMMENT ON TABLE model_files IS
'Files belonging to a repository revision and mapped to object storage';

-- migrate:down

DROP TABLE IF EXISTS model_files;
DROP TABLE IF EXISTS model_revisions;
DROP TRIGGER IF EXISTS update_model_repositories_updated_at ON model_repositories;
DROP FUNCTION IF EXISTS update_model_repositories_updated_at();
DROP TABLE IF EXISTS model_repositories;
