-- ===========================================================================
-- IMPORTANT! READ! DO NOT SKIP THIS!!
-- ===========================================================================
-- We need to follow an expand/contract pattern for db migrations for safety.
-- e.g. if you are replacing a column or doing anything that would BREAK running
--      services, stop. Do not do that. Instead, _expand_ the current schema to ONLY ADD
--      new things which are not breaking. Then, once everyone has completed that migration,
--      _contract_ the schema, actually doing the removal of anything you wanted to.
--
-- IMPORTANT QUESTIONS:
-- 1. Is this change backwards compatible with running application pods?
--      - Yes? Great, you're following the "expand" correctly. Now consider when and how you should "contract".
--      - No? Stop. You could break production. You need the OLD application code to work with the NEW database
--        and the NEW application code to work with the NEW database. Eventually, when you apply the "contract" migration, the
--        OLD logic can be safely removed (assuming everyone has migrated to the expansion).
-- 2. DO NOT drop or rename columns in an initial migration. Use a multi-stage rollout
--      - Add new column in one migration, remove old in a FUTURE migration after everyone is on the first one
-- 3. If you are only adding a heavy index, consider adding "transaction:false"
--    to the migrate line and use CREATE INDEX CONCURRENTLY.
--    Changing "-- migrate:up" to "-- migrate:up transaction:false" tells dbmate to turn OFF transactional
--    migrations.
--
--    If you don't do this and your migration takes a long time, it will block live operations (read/write).
--    You can use CONCURRENTLY to not block and allow read/write while
--    the action happens in the background in the db, but only if you tell dbmate to not put the whole migration
--    in a transaction.
--
--    NOTE: Heavy indexes may take longer than the statement_timeout default below. If building a large index,
--          manually add "SET statement_timeout = '0';" (disabled) or some other reasonable maximum. Just note
--          that postgres will kill a statement after that maximum.
--
-- ===========================================================================
-- UPGRADE MIGRATION SQL
-- ===========================================================================
-- migrate:up
--
-- ==== guardrails: prod safety ====
-- in postgres, while a migration waits for a lock, it blocks ALL live app traffic
-- behind it in the queue.
--
-- lock_timeout:      If the migration can't get a lock within n seconds (e.g. stuck
--                    behind a slow app query), it aborts safely to protect the live app traffic.
-- statement_timeout: If the migration gets the lock but takes longer than n seconds
--                    to run, it aborts so it doesn't hold the DB hostage.
SET lock_timeout = '10s';
SET statement_timeout = '60s';
-- ============================================================
-- MODELS
-- ============================================================

CREATE TABLE IF NOT EXISTS models (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    namespace TEXT NOT NULL,
    model_name TEXT NOT NULL,

    description TEXT,

    tags TEXT [] DEFAULT '{}',

    current_revision TEXT NOT NULL DEFAULT 'main',

    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT models_unique
    UNIQUE (namespace, model_name)
);

CREATE INDEX IF NOT EXISTS idx_models_namespace
ON models (namespace);

CREATE INDEX IF NOT EXISTS idx_models_current_revision
ON models (current_revision);

CREATE INDEX IF NOT EXISTS idx_models_created_at
ON models (created_at);

-- ============================================================
-- UPDATED_AT TRIGGER
-- ============================================================

CREATE OR REPLACE FUNCTION UPDATE_MODELS_UPDATED_AT()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_models_updated_at
ON models;

CREATE TRIGGER update_models_updated_at
BEFORE UPDATE
ON models
FOR EACH ROW
EXECUTE FUNCTION UPDATE_MODELS_UPDATED_AT();

-- ============================================================
-- MODEL REVISIONS
-- ============================================================

CREATE TABLE IF NOT EXISTS model_revisions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    model_id BIGINT NOT NULL
    REFERENCES models (id)
    ON DELETE CASCADE,

    revision_name TEXT NOT NULL DEFAULT 'main',

    revision_identifier TEXT NOT NULL,

    etag TEXT,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT model_revisions_unique_name
    UNIQUE (model_id, revision_name),

    CONSTRAINT model_revisions_unique_identifier
    UNIQUE (model_id, revision_identifier)
);

CREATE INDEX IF NOT EXISTS idx_model_revisions_model
ON model_revisions (model_id);

CREATE INDEX IF NOT EXISTS idx_model_revisions_identifier
ON model_revisions (revision_identifier);

CREATE INDEX IF NOT EXISTS idx_model_revisions_created_at
ON model_revisions (created_at);

DROP TRIGGER IF EXISTS update_model_revisions_updated_at
ON model_revisions;

CREATE TRIGGER update_model_revisions_updated_at
BEFORE UPDATE
ON model_revisions
FOR EACH ROW
EXECUTE FUNCTION UPDATE_MODELS_UPDATED_AT();

-- ============================================================
-- MODEL FILES
-- ============================================================

CREATE TABLE IF NOT EXISTS model_files (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    revision_id BIGINT NOT NULL
    REFERENCES model_revisions (id)
    ON DELETE CASCADE,

    file_path TEXT NOT NULL,

    s3_key TEXT NOT NULL,

    file_size BIGINT NOT NULL,

    content_sha TEXT NOT NULL,

    content_etag TEXT,

    file_type TEXT,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT model_files_unique
    UNIQUE (revision_id, file_path)
);

CREATE INDEX IF NOT EXISTS idx_model_files_revision
ON model_files (revision_id);

CREATE INDEX IF NOT EXISTS idx_model_files_sha
ON model_files (content_sha);

CREATE INDEX IF NOT EXISTS idx_model_files_s3_key
ON model_files (s3_key);

CREATE INDEX IF NOT EXISTS idx_model_files_created_at
ON model_files (created_at);

DROP TRIGGER IF EXISTS update_model_files_updated_at
ON model_files;

CREATE TRIGGER update_model_files_updated_at
BEFORE UPDATE
ON model_files
FOR EACH ROW
EXECUTE FUNCTION UPDATE_MODELS_UPDATED_AT();

-- ============================================================
-- COMMENTS
-- ============================================================

COMMENT ON TABLE models IS
'Top-level AI models similar to Hugging Face model entries';

COMMENT ON TABLE model_revisions IS
'Model revisions such as main, v1, v2 or commit references';

COMMENT ON TABLE model_files IS
'Model files mapped to object storage';

COMMENT ON COLUMN model_files.s3_key IS
'Object storage key (MinIO / AWS S3 compatible)';

COMMENT ON COLUMN model_revisions.revision_identifier IS
'Commit SHA or revision identifier';

-- ===========================================================================
-- DOWNGRADE MIGRATION SQL
-- ===========================================================================
-- migrate:down
SET lock_timeout = '10s';
SET statement_timeout = '60s';

DROP TABLE IF EXISTS model_files CASCADE;
DROP TABLE IF EXISTS model_revisions CASCADE;

DROP TRIGGER IF EXISTS update_models_updated_at
ON models;

DROP FUNCTION IF EXISTS update_models_updated_at();

DROP TABLE IF EXISTS models CASCADE;
