\restrict dbmate

-- Dumped from database version 18.4 (Homebrew)
-- Dumped by pg_dump version 18.4 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: update_model_repositories_updated_at(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.update_model_repositories_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: model_files; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.model_files (
    id bigint NOT NULL,
    revision_id bigint NOT NULL,
    file_path text NOT NULL,
    s3_key text NOT NULL,
    file_size bigint NOT NULL,
    content_sha text NOT NULL,
    content_etag text,
    file_type text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: TABLE model_files; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.model_files IS 'Repository files mapped to object storage';


--
-- Name: COLUMN model_files.s3_key; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.model_files.s3_key IS 'Object storage key (MinIO / AWS S3 compatible)';


--
-- Name: model_files_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.model_files ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.model_files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: model_repositories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.model_repositories (
    id bigint NOT NULL,
    namespace text NOT NULL,
    repo_name text NOT NULL,
    description text,
    tags text[] DEFAULT '{}'::text[],
    current_revision text DEFAULT 'main'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: TABLE model_repositories; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.model_repositories IS 'Top-level AI model repositories similar to Hugging Face repositories';


--
-- Name: model_repositories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.model_repositories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.model_repositories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: model_revisions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.model_revisions (
    id bigint NOT NULL,
    repository_id bigint NOT NULL,
    revision_name text DEFAULT 'main'::text NOT NULL,
    revision_identifier text NOT NULL,
    etag text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: TABLE model_revisions; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.model_revisions IS 'Repository revisions such as main, v1, v2 or commit references';


--
-- Name: COLUMN model_revisions.revision_identifier; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.model_revisions.revision_identifier IS 'Commit SHA or revision identifier';


--
-- Name: model_revisions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.model_revisions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.model_revisions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    version character varying NOT NULL
);


--
-- Name: model_files model_files_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_files
    ADD CONSTRAINT model_files_pkey PRIMARY KEY (id);


--
-- Name: model_files model_files_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_files
    ADD CONSTRAINT model_files_unique UNIQUE (revision_id, file_path);


--
-- Name: model_repositories model_repositories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_repositories
    ADD CONSTRAINT model_repositories_pkey PRIMARY KEY (id);


--
-- Name: model_repositories model_repositories_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_repositories
    ADD CONSTRAINT model_repositories_unique UNIQUE (namespace, repo_name);


--
-- Name: model_revisions model_revisions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_revisions
    ADD CONSTRAINT model_revisions_pkey PRIMARY KEY (id);


--
-- Name: model_revisions model_revisions_unique_identifier; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_revisions
    ADD CONSTRAINT model_revisions_unique_identifier UNIQUE (repository_id, revision_identifier);


--
-- Name: model_revisions model_revisions_unique_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_revisions
    ADD CONSTRAINT model_revisions_unique_name UNIQUE (repository_id, revision_name);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);


--
-- Name: idx_model_files_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_model_files_created_at ON public.model_files USING btree (created_at);


--
-- Name: idx_model_files_path; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_model_files_path ON public.model_files USING btree (revision_id, file_path);


--
-- Name: idx_model_files_revision; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_model_files_revision ON public.model_files USING btree (revision_id);


--
-- Name: idx_model_files_sha; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_model_files_sha ON public.model_files USING btree (content_sha);


--
-- Name: idx_model_files_s3_key; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_model_files_s3_key ON public.model_files USING btree (s3_key);


--
-- Name: idx_model_repositories_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_model_repositories_created_at ON public.model_repositories USING btree (created_at);


--
-- Name: idx_model_repositories_current_revision; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_model_repositories_current_revision ON public.model_repositories USING btree (current_revision);


--
-- Name: idx_model_repositories_namespace; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_model_repositories_namespace ON public.model_repositories USING btree (namespace);


--
-- Name: idx_model_repositories_namespace_repo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_model_repositories_namespace_repo ON public.model_repositories USING btree (namespace, repo_name);


--
-- Name: idx_model_revisions_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_model_revisions_created_at ON public.model_revisions USING btree (created_at);


--
-- Name: idx_model_revisions_identifier; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_model_revisions_identifier ON public.model_revisions USING btree (revision_identifier);


--
-- Name: idx_model_revisions_repository; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_model_revisions_repository ON public.model_revisions USING btree (repository_id);


--
-- Name: idx_model_revisions_revision; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_model_revisions_revision ON public.model_revisions USING btree (repository_id, revision_name);


--
-- Name: model_repositories update_model_repositories_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER update_model_repositories_updated_at BEFORE UPDATE ON public.model_repositories FOR EACH ROW EXECUTE FUNCTION public.update_model_repositories_updated_at();


--
-- Name: model_files model_files_revision_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_files
    ADD CONSTRAINT model_files_revision_id_fkey FOREIGN KEY (revision_id) REFERENCES public.model_revisions(id) ON DELETE CASCADE;


--
-- Name: model_revisions model_revisions_repository_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_revisions
    ADD CONSTRAINT model_revisions_repository_id_fkey FOREIGN KEY (repository_id) REFERENCES public.model_repositories(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict dbmate


--
-- Dbmate schema migrations
--

INSERT INTO public.schema_migrations (version) VALUES
    ('20260712145829');
