\restrict dbmate

-- Dumped from database version 18.4 (Homebrew)
-- Dumped by pg_dump version 18.4 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: update_models_updated_at(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.update_models_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: model_files; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.model_files (
    id bigint NOT NULL,
    revision_id bigint NOT NULL,
    file_path text NOT NULL,
    s3_key text CONSTRAINT model_files_storage_key_not_null NOT NULL,
    file_size bigint NOT NULL,
    content_sha text NOT NULL,
    content_etag text,
    file_type text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: TABLE model_files; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.model_files IS 'Model files mapped to object storage';


--
-- Name: COLUMN model_files.s3_key; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.model_files.s3_key IS 'Object storage key (MinIO / AWS S3 compatible)';


--
-- Name: model_files_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.model_files ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.model_files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: models; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.models (
    id bigint CONSTRAINT models_id_not_null NOT NULL,
    namespace text CONSTRAINT models_namespace_not_null NOT NULL,
    model_name text CONSTRAINT models_model_name_not_null NOT NULL,
    description text,
    tags text[] DEFAULT '{}'::text[],
    current_revision text DEFAULT 'main'::text CONSTRAINT models_current_revision_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: TABLE models; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.models IS 'Top-level AI models similar to Hugging Face model entries';


--
-- Name: models_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.models ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.models_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: model_revisions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.model_revisions (
    id bigint NOT NULL,
    model_id bigint CONSTRAINT model_revisions_model_id_fkey NOT NULL,
    revision_name text DEFAULT 'main'::text NOT NULL,
    revision_identifier text NOT NULL,
    etag text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: TABLE model_revisions; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.model_revisions IS 'Model revisions such as main, v1, v2 or commit references';


--
-- Name: COLUMN model_revisions.revision_identifier; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.model_revisions.revision_identifier IS 'Commit SHA or revision identifier';


--
-- Name: model_revisions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.model_revisions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.model_revisions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    version character varying NOT NULL
);


--
-- Name: model_files model_files_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_files
    ADD CONSTRAINT model_files_pkey PRIMARY KEY (id);


--
-- Name: model_files model_files_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_files
    ADD CONSTRAINT model_files_unique UNIQUE (revision_id, file_path);


--
-- Name: models models_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.models
    ADD CONSTRAINT models_pkey PRIMARY KEY (id);


--
-- Name: models models_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.models
    ADD CONSTRAINT models_unique UNIQUE (namespace, model_name);


--
-- Name: model_revisions model_revisions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_revisions
    ADD CONSTRAINT model_revisions_pkey PRIMARY KEY (id);


--
-- Name: model_revisions model_revisions_unique_identifier; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_revisions
    ADD CONSTRAINT model_revisions_unique_identifier UNIQUE (model_id, revision_identifier);


--
-- Name: model_revisions model_revisions_unique_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_revisions
    ADD CONSTRAINT model_revisions_unique_name UNIQUE (model_id, revision_name);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);


--
-- Name: idx_model_files_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_model_files_created_at ON public.model_files USING btree (created_at);


--
-- Name: idx_model_files_path; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_model_files_path ON public.model_files USING btree (revision_id, file_path);


--
-- Name: idx_model_files_revision; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_model_files_revision ON public.model_files USING btree (revision_id);


--
-- Name: idx_model_files_s3_key; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_model_files_s3_key ON public.model_files USING btree (s3_key);


--
-- Name: idx_model_files_sha; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_model_files_sha ON public.model_files USING btree (content_sha);


--
-- Name: idx_model_files_s3_key; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_model_files_s3_key ON public.model_files USING btree (s3_key);


--
-- Name: idx_models_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_models_created_at ON public.models USING btree (created_at);


--
-- Name: idx_models_current_revision; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_models_current_revision ON public.models USING btree (current_revision);


--
-- Name: idx_models_namespace; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_models_namespace ON public.models USING btree (namespace);


--
--
-- Name: idx_model_revisions_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_model_revisions_created_at ON public.model_revisions USING btree (created_at);


--
-- Name: idx_model_revisions_identifier; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_model_revisions_identifier ON public.model_revisions USING btree (revision_identifier);


--
-- Name: idx_model_revisions_model; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_model_revisions_model ON public.model_revisions USING btree (model_id);


--
-- Name: models update_models_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER update_models_updated_at BEFORE UPDATE ON public.models FOR EACH ROW EXECUTE FUNCTION public.update_models_updated_at();


--
-- Name: model_revisions update_model_revisions_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER update_model_revisions_updated_at BEFORE UPDATE ON public.model_revisions FOR EACH ROW EXECUTE FUNCTION public.update_models_updated_at();


--
-- Name: models update_models_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER update_models_updated_at BEFORE UPDATE ON public.models FOR EACH ROW EXECUTE FUNCTION public.update_models_updated_at();


--
-- Name: model_files model_files_revision_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_files
    ADD CONSTRAINT model_files_revision_id_fkey FOREIGN KEY (revision_id) REFERENCES public.model_revisions(id) ON DELETE CASCADE;


--
-- Name: model_revisions model_revisions_model_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_revisions
    ADD CONSTRAINT model_revisions_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.models(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict dbmate


--
-- Dbmate schema migrations
--

INSERT INTO public.schema_migrations (version) VALUES
    ('20260712145829'),
    ('20260713142638'),
    ('20260721110000');
