import json
from copy import deepcopy
from pathlib import Path

SERVICE_SPECS = [
    ("gen3_ai_model_repo", Path("services/gen3_ai_model_repo/docs/autogenerated_openapi.json"), "/gen3_ai_model_repo"),
    ("gen3_embeddings", Path("services/gen3_embeddings/docs/autogenerated_openapi.json"), "/gen3_embeddings"),
    ("gen3_inference", Path("services/gen3_inference/docs/autogenerated_openapi.json"), "/gen3_inference"),
]

# TODO: If we can have a single uv workspace with all services, then redo this
#       (e.g. move the logic in the separate /services/foo/generate_openapi.py into THIS script and
#        delete the copies per service)

OUTPUT_PATH = Path("docs/autogenerated_openapi.json")

def merge_openapi(service_specs):
    base = {
        "openapi": "3.1.0",
        "info": {
            "title": "Gen3 AI",
            "version": "1.0.0",
            "description": (
                "Gen3 AI API."
            ),
        },
        "servers": [
            {
                "url": "http://localhost:4141",
                "description": "Local Development: gen3_ai_model_repo"
            },
            {
                "url": "http://localhost:4142",
                "description": "Local Development: gen3_embeddings"
            },
            {
                "url": "http://localhost:4143",
                "description": "Local Development: gen3_inference"
            },
            {
                "url": "https://example.com/ai",
                "description": "Production"
            },
        ],
        "paths": {},
        "components": {
            "schemas": {},
            "parameters": {},
            "responses": {},
            "securitySchemes": {
                "bearerAuth": {
                    "type": "http",
                    "scheme": "bearer",
                    "bearerFormat": "JWT",
                }
            },
        },
        "tags": [],
    }

    base["security"] = [{"bearerAuth": []}]


    # TODO: add authorization support?

    for service_name, path, prefix in service_specs:
        if not path.exists():
            print(f"Warning: Spec for {service_name} not found at {path}")
            continue

        spec = json.loads(path.read_text())

        # paths
        for api_path, item in spec.get("paths", {}).items():
            # ignore version and status endpoints since they
            # are only intended for internal health and version
            # checking and expose service info. This aggregated
            # API is intended to provide the higher-level general
            # use API.
            if "_version" in api_path or "_status" in api_path:
                continue
            base["paths"].setdefault(api_path, item)

        # components
        sub_components = spec.get("components", {})
        for comp_type, comp_dict in sub_components.items():
            if comp_type not in base["components"]:
                base["components"][comp_type] = {}
            for name, value in comp_dict.items():
                base["components"][comp_type][name] = value

        # tags
        existing_names = {t["name"] for t in base["tags"] if "name" in t}
        for tag in spec.get("tags", []):
            tag_name = tag.get("name")
            if not tag_name:
                continue
            if tag_name not in existing_names:
                base["tags"].append(
                    {
                        "name": tag_name,
                        **{k: v for k, v in tag.items() if k != "name"},
                    }
                )

    return base


def main():
    aggregated = merge_openapi(SERVICE_SPECS)
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(json.dumps(aggregated, indent=2))
    print(f"Wrote aggregated OpenAPI schema to {OUTPUT_PATH}")

if __name__ == "__main__":
    main()
