\restrict dbmate

-- Dumped from database version 18.1 (Homebrew)
-- Dumped by pg_dump version 18.1 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: ltree; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS ltree WITH SCHEMA public;


--
-- Name: EXTENSION ltree; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION ltree IS 'data type for hierarchical tree-like structures';


--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


--
-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: collections; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.collections (
    id bigint NOT NULL,
    collection_name text NOT NULL,
    description text,
    ai_model_name text,
    dimensions integer NOT NULL,
    vector_type text DEFAULT 'vector'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: collections_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.collections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.collections_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: embeddings_halfvec; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.embeddings_halfvec (
    collection_id bigint,
    embedding_id uuid DEFAULT gen_random_uuid() NOT NULL,
    embedding public.halfvec NOT NULL,
    embedding_hash uuid NOT NULL,
    authz text NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb,
    metadata_hash uuid,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: embeddings_vector; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.embeddings_vector (
    collection_id bigint,
    embedding_id uuid DEFAULT gen_random_uuid() NOT NULL,
    embedding public.vector NOT NULL,
    embedding_hash uuid NOT NULL,
    authz text NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb,
    metadata_hash uuid,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    version character varying NOT NULL
);


--
-- Name: collections collections_collection_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collections
    ADD CONSTRAINT collections_collection_name_key UNIQUE (collection_name);


--
-- Name: collections collections_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collections
    ADD CONSTRAINT collections_pkey PRIMARY KEY (id);


--
-- Name: embeddings_halfvec embeddings_halfvec_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.embeddings_halfvec
    ADD CONSTRAINT embeddings_halfvec_pkey PRIMARY KEY (embedding_id);


--
-- Name: embeddings_halfvec embeddings_halfvec_uniq_collection_embhash; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.embeddings_halfvec
    ADD CONSTRAINT embeddings_halfvec_uniq_collection_embhash UNIQUE (collection_id, embedding_hash, metadata_hash, authz);


--
-- Name: embeddings_halfvec embeddings_halfvec_uniq_collection_uuid; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.embeddings_halfvec
    ADD CONSTRAINT embeddings_halfvec_uniq_collection_uuid UNIQUE (collection_id, embedding_id);


--
-- Name: embeddings_vector embeddings_vector_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.embeddings_vector
    ADD CONSTRAINT embeddings_vector_pkey PRIMARY KEY (embedding_id);


--
-- Name: embeddings_vector embeddings_vector_uniq_collection_embhash; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.embeddings_vector
    ADD CONSTRAINT embeddings_vector_uniq_collection_embhash UNIQUE (collection_id, embedding_hash, metadata_hash, authz);


--
-- Name: embeddings_vector embeddings_vector_uniq_collection_uuid; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.embeddings_vector
    ADD CONSTRAINT embeddings_vector_uniq_collection_uuid UNIQUE (collection_id, embedding_id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);


--
-- Name: idx_embeddings_halfvec_authz; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_embeddings_halfvec_authz ON public.embeddings_halfvec USING btree (authz);


--
-- Name: idx_embeddings_halfvec_metadata_gin; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_embeddings_halfvec_metadata_gin ON public.embeddings_halfvec USING gin (metadata);


--
-- Name: idx_embeddings_vector_authz; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_embeddings_vector_authz ON public.embeddings_vector USING btree (authz);


--
-- Name: idx_embeddings_vector_metadata_gin; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_embeddings_vector_metadata_gin ON public.embeddings_vector USING gin (metadata);


--
-- Name: embeddings_halfvec embeddings_halfvec_collection_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.embeddings_halfvec
    ADD CONSTRAINT embeddings_halfvec_collection_id_fkey FOREIGN KEY (collection_id) REFERENCES public.collections(id) ON DELETE CASCADE;


--
-- Name: embeddings_vector embeddings_vector_collection_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.embeddings_vector
    ADD CONSTRAINT embeddings_vector_collection_id_fkey FOREIGN KEY (collection_id) REFERENCES public.collections(id) ON DELETE CASCADE;


--
-- Name: embeddings_halfvec authz_policy_halfvec; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY authz_policy_halfvec ON public.embeddings_halfvec USING ((authz = ANY ((current_setting('app.allowed_authz'::text, true))::text[]))) WITH CHECK ((authz = ANY ((current_setting('app.allowed_authz'::text, true))::text[])));


--
-- Name: embeddings_vector authz_policy_vector; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY authz_policy_vector ON public.embeddings_vector USING ((authz = ANY ((current_setting('app.allowed_authz'::text, true))::text[]))) WITH CHECK ((authz = ANY ((current_setting('app.allowed_authz'::text, true))::text[])));


--
-- Name: embeddings_halfvec; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.embeddings_halfvec ENABLE ROW LEVEL SECURITY;

--
-- Name: embeddings_vector; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.embeddings_vector ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict dbmate


--
-- Dbmate schema migrations
--

INSERT INTO public.schema_migrations (version) VALUES
    ('20260622162416');
