name: Weekly Automatic Updates to API Docs & Tool Versions
on:
  # allow manual runs
  workflow_dispatch:

  # also schedule weekly
  schedule:
    # 9:17AM central time Monday
    # why so specific? probably a lot of people have things scheduled
    # on the half-hour so this avoids load times at 9 / 9:30
    - cron: '17 9 * * 1'
      timezone: "America/Chicago"
permissions:
  contents: write
  pull-requests: write
jobs:
  update-check:
    runs-on: ubuntu-latest
    env:
      UV_VERSION: '0.11.8'
      JUST_VERSION: '1.50.0'
      PYTHON_VERSION: '3.13'
      PGHOST: 'localhost'
      PGPORT: 5432
      PGUSER: 'postgres'
    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          # this uses the default repo-scoped, job-used GITHUB_TOKEN
          # and saves it as git creds for this run only (it's
          # removed in a post cleanup). this ensures
          # future git commands are authed
          persist-credentials: true

      - name: Set up python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: python info
        run: python --version

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/${{ env.UV_VERSION }}/install.sh | sh

      - uses: taiki-e/install-action@v2
        with:
          tool: just@${{ env.JUST_VERSION }}

      - name: just setup
        run: |
          just setup

      - name: just install
        run: |
          just install

      # we need node for use of redocly by `just openapi`
      # so use the official GH action for this
      - uses: actions/setup-node@v6

      # autoupdate API docs
      - name: just openapi
        run: |
          just openapi

      # autoupdate versions of tools used in workflows
      - name: just update_versions
        run: |
          just update_versions

      # will format and fix files
      - name: format and fix files with `pre-commit run -a`
        run: |
          # force positive exit code.
          # pre-commit errors when files have to be formatted but automatically
          # does the formatting. Also we haven't created a branch yet so that will fail too.
          # So exit successfully here no matter what, and if there
          # is a real issue, it will be captured by the resulting PR automation checks
          pre-commit run -a || true

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Check for file changes
        id: check_changes
        run: |
          git add ./docs/api.html
          git add ./docs/autogenerated_openapi.json
          git add ./services/*/docs/autogenerated_openapi.json
          git add ./.github/workflows/*.yml

          # if existing secrets just moved line numbers
          # note: if detect-secrets actually fails on a NEW false
          # positive secret from the docs generation,
          # this workflow will still fail and require human intervention
          git add .secrets.baseline

          if git diff --cached --quiet; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request If Changes Detected
        if: steps.check_changes.outputs.changes == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="chore/update-docs-and-versions-${{ github.run_id }}"
          git checkout -b $BRANCH_NAME

          git add ./docs/api.html
          git add ./docs/autogenerated_openapi.json
          git add ./services/*/docs/autogenerated_openapi.json
          git add ./.github/workflows/*.yml

          # if existing secrets just moved line numbers
          # note: if detect-secrets actually fails on a NEW false
          # positive secret from the docs generation,
          # this workflow will still fail and require human intervention
          git add .secrets.baseline

          git commit -m "chore(docs-and-versions): update API documentation and versions in workflows"
          git push origin $BRANCH_NAME

          # gh CLI is pre-installed in ubuntu-latest
          # NOTE: --draft is required b/c the default GITHUB_TOKEN (which is used here)
          #       will not trigger future `on: push` actions in the resulting PR. This is
          #       a GH-required protection to prevent accidental infinite loops. To work around
          #       this, we make the PR a draft, require a real person to manually "mark it ready"
          #       and then the `automation.yml` workflow actions should run b/c we explicitly
          #       tell it to run on a PR "ready" trigger.
          gh pr create \
            --title "chore(docs-and-versions): update API documentation and versions in workflows" \
            --body "Automated update of APIs docs and versions in workflows." \
            --head $BRANCH_NAME \
            --draft
